version: "3"
services:
  db_test:
    image: postgres
    container_name: db_test
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.test

  nest_app:
    container_name: nest_app
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 3000:3000
    env_file:
      - .env.test
    depends_on:
      - db_test
