version: "3"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.docker
    healthcheck:
      test: pg_isready -U postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  nest_app:
    container_name: nest_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres:
