name: ServerCI/CD
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  TestAndDeploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Make tests envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "primeflix_test"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@db_test:5432/primeflix_test?schema=public"
          directory: server
          file_name: .env.test

      - name: Run tests
        run: docker-compose -f server/docker-compose.test.yml up --exit-code-from nest_app_tests

      - name: Deploy to heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: "main"
          appdir: "server"
